---
# SPDX-FileCopyrightText: 2026 Damián Búho <damian.buho@proton.me>
# SPDX-License-Identifier: MIT

# pf-cli-managed: yes
tagFormat: ${version}
branches:
  - name: main
    channel: latest
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/gitea"
    - giteaUrl: https://kiota.ch
